language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

addons:
  apt:
    update: true

# command to install dependencies
install:
  - pip install coveralls
  - pip install .

# command to run tests
script:
  - coverage run setup.py test

# after_success:
#   - coveralls

# notifications:
#   email:
#     - "john.g.evans.ne@gmail.com"
#     - "lars@hankat.dk"
